In [1]:
# Dependencies
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [2]:
# Data loading
file_path = '../Dataset/day_approach_maskedID_timeseries.csv'
df = pd.read_csv(file_path)

In [3]:
# Split of datasets
injury_df = df[df['injury']==1]
healthy_df = df[df['injury']==0]

# Injury data points are clearly unbalanced
print(f'Injury data points: {injury_df.shape[0]}')
print(f'Healthy data points: {healthy_df.shape[0]}')
print(f'Proportion of injury data points among the data set: {injury_df.shape[0] / (injury_df.shape[0] + healthy_df.shape[0])}')

Injury data points: 583
Healthy data points: 42183
Proportion of injury data points among the data set: 0.013632324743955478

In [4]:
# Count of data points, injury points and injury proportion per athlete 
athlete_analysis = (
    df.groupby("Athlete ID", as_index=False)
      .agg(
          data_points=("injury", "size"),      # rows per athlete
          injury_events=("injury", "sum")      # number of injury=1 rows
      )
)

athlete_analysis["injury_proportion"] = (
    athlete_analysis["injury_events"] / athlete_analysis["data_points"]
)

athlete_analysis

    Athlete ID  data_points  injury_events  injury_proportion
0            0          310              7           0.022581
1            1          461              2           0.004338
2            2         1291              4           0.003098
3            3          344              3           0.008721
4            4          681              7           0.010279
..         ...          ...            ...                ...
69          69          314              5           0.015924
70          70          327              5           0.015291
71          71          392              5           0.012755
72          72          216              0           0.000000
73          73          192              0           0.000000

[74 rows x 4 columns]

In [5]:
# Summary stats for data point counts
count_stats = athlete_analysis["data_points"].agg(["max", "min", "mean", "std"])

# Summary stats for injury event counts
injury_event_stats = athlete_analysis["injury_events"].agg(["max", "min", "mean", "std"])

# Summary stats for injury proportion
injury_prop_stats = athlete_analysis["injury_proportion"].agg(["max", "min", "mean", "std"])

print("Data points per athlete stats:")
print(count_stats)

print("\nInjury events per athlete stats:")
print(injury_event_stats)

print("\nInjury proportion per athlete stats:")
print(injury_prop_stats)

# We can say that each athlete has around 600 recorded training whereby 7 lead to injury

Data points per athlete stats:
max     1791.000000
min       43.000000
mean     577.918919
std      425.929274
Name: data_points, dtype: float64

Injury events per athlete stats:
max     35.000000
min      0.000000
mean     7.878378
std      8.261070
Name: injury_events, dtype: float64

Injury proportion per athlete stats:
max     0.045205
min     0.000000
mean    0.012959
std     0.011092
Name: injury_proportion, dtype: float64

In [6]:
# Table representing in descending injury proportion of athletes
print("\nAthlete-level analysis:")
print(
    athlete_analysis.sort_values(
        by=["injury_proportion", "injury_events", "data_points"],
        ascending=[False, False, False]
    ).to_string(index=False)
)

Athlete-level analysis:
 Athlete ID  data_points  injury_events  injury_proportion
         29          730             33           0.045205
         42          744             32           0.043011
         26          884             35           0.039593
         36          638             22           0.034483
         68          235              8           0.034043
         56          510             17           0.033333
         65          323             10           0.030960
         53          197              6           0.030457
         35          254              7           0.027559
          8          268              7           0.026119
         10          387             10           0.025840
         64          352              8           0.022727
          0          310              7           0.022581
         58          623             14           0.022472
         38          843             18           0.021352
         57          666             14           0.021021
         55           48              1           0.020833
         21          290              6           0.020690
          9         1233             23           0.018654
         23         1393             24           0.017229
          7          304              5           0.016447
         27         1344             22           0.016369
         40          308              5           0.016234
         17          873             14           0.016037
         50          814             13           0.015971
         69          314              5           0.015924
         67          517              8           0.015474
         70          327              5           0.015291
         28          280              4           0.014286
         22         1478             21           0.014208
         41         1393             18           0.012922
         71          392              5           0.012755
         47         1072             13           0.012127
         18          542              6           0.011070
         14          272              3           0.011029
         48          381              4           0.010499
          4          681              7           0.010279
         43         1471             15           0.010197
         59          725              7           0.009655
         52          957              9           0.009404
          3          344              3           0.008721
         61          956              8           0.008368
         16          365              3           0.008219
         51          254              2           0.007874
         39          130              1           0.007692
         33          391              3           0.007673
          6          534              4           0.007491
         32         1791             13           0.007259
         37         1242              9           0.007246
         20         1723             12           0.006965
         44          581              4           0.006885
         54         1207              8           0.006628
         45          507              3           0.005917
         66          176              1           0.005682
         19          584              3           0.005137
          5          215              1           0.004651
          1          461              2           0.004338
         24          756              3           0.003968
         63          516              2           0.003876
         13          318              1           0.003145
          2         1291              4           0.003098
         49          512              1           0.001953
         34          548              1           0.001825
         46          272              0           0.000000
         31          231              0           0.000000
         72          216              0           0.000000
         25          196              0           0.000000
         30          196              0           0.000000
         62          196              0           0.000000
         73          192              0           0.000000
         12          169              0           0.000000
         11          154              0           0.000000
         15          126              0           0.000000
         60           43              0           0.000000

In [7]:
injury_df.head(30)

,nr. sessions,total km,km Z3-4,km Z5-T1-T2,km sprinting,strength training,hours alternative,perceived exertion,perceived trainingSuccess,perceived recovery,...,km Z5-T1-T2.6,km sprinting.6,strength training.6,hours alternative.6,perceived exertion.6,perceived trainingSuccess.6,perceived recovery.6,Athlete ID,injury,Date
42183,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.08,0.00,0.18,...,0.0,0.0,0.0,0.00,0.08,0.00,0.17,0,1,324
42184,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.01,-0.01,-0.01,...,0.0,0.0,0.0,1.00,0.08,0.00,0.17,0,1,353
42185,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.01,-0.01,-0.01,...,0.0,0.0,0.0,0.00,-0.01,-0.01,-0.01,0,1,386
42186,1.0,7.5,4.0,0.0,0.0,0.0,0.0,0.10,0.00,0.18,...,0.0,0.0,0.0,1.50,0.08,0.00,0.17,0,1,413
42187,1.0,3.5,0.0,0.0,0.5,0.0,0.0,0.08,0.00,0.18,...,0.9,0.0,0.0,0.00,0.10,0.00,0.18,0,1,461
42188,1.0,6.9,3.9,0.0,0.0,0.0,0.0,0.09,0.00,0.17,...,0.0,0.0,0.0,1.00,0.08,0.00,0.17,0,1,490
42189,1.0,4.9,0.0,0.4,0.0,0.0,0.0,0.09,0.00,0.18,...,0.0,0.0,0.0,0.00,-0.01,-0.01,-0.01,0,1,528
42190,1.0,16.0,0.0,0.0,0.0,0.0,0.0,0.07,0.14,0.31,...,0.0,0.0,0.0,0.00,0.17,0.65,0.32,1,1,672
42191,1.0,15.0,0.0,0.0,0.0,0.0,0.0,0.10,0.87,0.18,...,10.0,0.0,0.0,0.00,0.59,0.53,0.35,1,1,765
42192,2.0,24.0,0.0,6.0,0.0,0.0,0.0,0.77,0.78,0.16,...,0.0,0.0,0.0,0.00,-0.01,-0.01,-0.01,2,1,680
42193,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.01,-0.01,-0.01,...,0.0,0.0,0.0,0.00,0.10,0.89,0.28,2,1,710
42194,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.01,-0.01,-0.01,...,0.0,0.0,1.0,1.33,0.31,0.58,0.32,2,1,1201
42195,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.01,-0.01,-0.01,...,0.0,0.0,0.0,0.00,0.34,0.57,0.27,2,1,1513
42196,2.0,12.5,0.0,0.0,0.0,1.0,0.0,0.13,0.00,0.10,...,6.0,0.0,0.0,0.00,0.16,0.00,0.09,3,1,310
42197,1.0,9.0,0.0,0.0,0.0,1.0,0.0,0.12,0.00,0.08,...,6.0,0.0,0.0,0.00,0.15,0.00,0.12,3,1,401
42198,1.0,14.5,3.0,0.0,0.0,0.0,0.0,0.13,0.00,0.11,...,0.0,0.0,0.0,0.00,0.12,0.00,0.09,3,1,476
42199,1.0,13.0,0.0,0.0,0.0,0.0,0.0,0.12,0.00,0.13,...,6.0,0.0,0.0,0.00,0.17,0.00,0.12,4,1,303
42200,1.0,8.0,0.0,0.0,0.0,1.0,0.0,0.14,0.00,0.11,...,0.0,0.0,0.0,0.00,0.12,0.00,0.13,4,1,455
42201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.01,-0.01,-0.01,...,0.0,0.0,0.0,0.00,0.39,0.72,0.22,4,1,722
42202,1.0,12.0,0.0,6.0,0.0,1.0,0.0,0.43,0.72,0.21,...,0.0,0.0,0.0,0.00,-0.01,-0.01,-0.01,4,1,747
42203,1.0,14.0,0.0,0.0,0.0,0.0,0.0,0.40,0.60,0.70,...,0.0,0.0,1.0,0.00,0.56,0.40,0.54,4,1,794
42204,1.0,12.0,0.0,0.0,0.0,1.0,0.0,0.56,0.66,0.34,...,0.0,0.0,0.0,0.00,0.65,0.74,0.12,4,1,827
42205,1.0,5.0,0.0,0.0,0.0,0.0,0.0,0.40,0.32,0.78,...,0.0,0.0,0.0,2.17,0.67,0.79,0.19,4,1,1589
42206,1.0,5.0,0.0,0.0,5.0,0.0,0.0,0.16,0.00,0.17,...,0.0,9.8,0.0,0.00,0.13,0.00,0.17,5,1,246
42207,1.0,12.0,5.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,...,0.0,0.0,1.0,0.00,0.13,0.00,0.14,6,1,348
42208,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.15,0.00,0.15,...,4.5,0.3,0.0,0.00,0.00,0.00,0.00,6,1,401
42209,1.0,7.9,0.0,3.6,0.3,0.0,0.0,0.16,0.00,0.12,...,0.0,0.0,0.0,0.00,0.14,0.00,0.13,6,1,453
42210,1.0,8.0,0.0,1.0,0.0,0.0,0.0,0.94,0.30,0.21,...,0.0,0.0,0.0,0.75,0.36,0.64,0.57,6,1,673
42211,1.0,9.3,0.0,0.0,0.3,0.0,0.0,0.12,0.00,0.13,...,6.0,0.0,0.0,0.00,0.15,0.00,0.14,7,1,310
42212,1.0,8.0,0.0,0.0,1.0,0.0,0.0,0.13,0.00,0.14,...,0.0,0.0,0.0,0.00,0.13,0.00,0.12,7,1,441

In [8]:
# Create processing dataframe
processed_df = df.copy()

# Sort chronologically inside each athlete
processed_df = (
    processed_df
    .sort_values(["Athlete ID", "Date"])
    .reset_index(drop=True)
)

# Time gap feature days between consecutive records of same athlete
processed_df["transition_period_days"] = (
    processed_df
    .groupby("Athlete ID")["Date"]
    .diff()
    .fillna(0)
    .astype(int)
)

# Transition feature from previous injury state to current injury state
prev_injury = (
    processed_df
    .groupby("Athlete ID")["injury"]
    .shift(1)
    .fillna(0)
    .astype(int)
)
curr_injury = processed_df["injury"].astype(int)

processed_df["transition"] = prev_injury.astype(str) + "->" + curr_injury.astype(str)

# Numeric encoding for model use
transition_map = {"0->0": 0, "0->1": 1, "1->0": 2, "1->1": 3}
processed_df["transition_code"] = processed_df["transition"].map(transition_map).astype("Int64")

# Cumulated injury per athlete (running total)
processed_df["cumulated_injury"] = (
    processed_df
    .groupby("Athlete ID")["injury"]
    .cumsum()
    .astype(int)
)

# Quick check
processed_df[
    ["Athlete ID", "injury", "transition_period_days", "transition", "cumulated_injury"]
].head(30)

    Athlete ID  injury  transition_period_days transition  cumulated_injury
0            0       0                       0       0->0                 0
1            0       0                       1       0->0                 0
2            0       0                       1       0->0                 0
3            0       0                       1       0->0                 0
4            0       0                       1       0->0                 0
5            0       0                       1       0->0                 0
6            0       0                       1       0->0                 0
7            0       0                       1       0->0                 0
8            0       0                       1       0->0                 0
9            0       0                       1       0->0                 0
10           0       0                       1       0->0                 0
11           0       0                       1       0->0                 0
12           0       0                       1       0->0                 0
13           0       0                       1       0->0                 0
14           0       0                       1       0->0                 0
15           0       0                       1       0->0                 0
16           0       0                       1       0->0                 0
17           0       0                       1       0->0                 0
18           0       0                       1       0->0                 0
19           0       0                       1       0->0                 0
20           0       0                       1       0->0                 0
21           0       0                       1       0->0                 0
22           0       0                       1       0->0                 0
23           0       0                       1       0->0                 0
24           0       0                       1       0->0                 0
25           0       0                       1       0->0                 0
26           0       0                       1       0->0                 0
27           0       0                       1       0->0                 0
28           0       0                       1       0->0                 0
29           0       0                       1       0->0                 0

In [9]:
# Counts and proportion of transitions
transition_counts = processed_df["transition"].value_counts().sort_index()
transition_props = processed_df["transition"].value_counts(normalize=True).sort_index()

# Statistical summary (0->0 dominates heavily)
transition_stats = pd.DataFrame({
    "count": transition_counts,
    "proportion": transition_props
})

print("Transition type stats:")
print(transition_stats)

Transition type stats:
            count  proportion
transition
0->0        41818    0.977833
0->1          393    0.009190
1->0          365    0.008535
1->1          190    0.004443

In [10]:
# Stastiscal summary of transition period days
tp = processed_df["transition_period_days"]

print("\nTransition period days - overall descriptive stats:")
print(tp.describe(percentiles=[0.5, 0.75, 0.9, 0.95, 0.99]))

print("\nExtra checks:")
print("Mean:", tp.mean())
print("Std :", tp.std())
print("Min :", tp.min())
print("Max :", tp.max())
print("Rows with gap > 1 day:", (tp > 1).sum())
print("Rows with gap > 10 days:", (tp > 10).sum())

Transition period days - overall descriptive stats:
count    42766.000000
mean         1.830917
std          8.105724
min          0.000000
50%          1.000000
75%          1.000000
90%          1.000000
95%          1.000000
99%         25.000000
max        649.000000
Name: transition_period_days, dtype: float64

Extra checks:
Mean: 1.8309170836645934
Std : 8.10572365834997
Min : 0
Max : 649
Rows with gap > 1 day: 992
Rows with gap > 10 days: 974

In [11]:
# Statistical summary of transition period days per transition types
tp_by_transition = (
    processed_df
    .groupby("transition")["transition_period_days"]
    .agg(["count", "mean", "std", "min", "median", "max"])
    .sort_index()
)

print("\nTransition period by transition type:")
print(tp_by_transition)

Transition period by transition type:
            count       mean        std  min  median  max
transition
0->0        41818   1.093787   4.901191    0     1.0  649
0->1          393  26.076336  22.393610    0    22.0  259
1->0          365  34.767123  25.139020   22    25.0  236
1->1          190  50.647368  38.226378   22    40.0  278

In [12]:
# Statistical summary of transition period days per athlete
athlete_gap_stats = (
    processed_df
    .groupby("Athlete ID")["transition_period_days"]
    .agg(["count", "mean", "std", "max"])
    .sort_values("max", ascending=False)
)

print("\nTop athletes by largest observed gap:")
print(athlete_gap_stats.head(10))

Top athletes by largest observed gap:
            count      mean        std  max
Athlete ID
48            381  3.238845  33.454654  649
37           1242  1.792271  13.333883  435
4             681  2.333333  17.407289  422
18            542  2.293358  14.762091  278
9            1233  2.150041   9.830679  273
38            843  2.523132  11.482833  262
1             461  1.659436  12.111935  259
33            391  2.020460  12.629822  236
36            638  3.101881  12.895692  235
43           1471  1.597553   6.563854  213

In [13]:
# Count of gaps > 1 day per athlete and transition type
gaps_gt1_by_athlete_type = (
    processed_df[processed_df["transition_period_days"] > 1]
    .groupby(["Athlete ID", "transition"])
    .size()
    .rename("gaps_gt_1")
    .reset_index()
    .sort_values(["Athlete ID", "gaps_gt_1"], ascending=[True, False])
)

print("\nGaps > 1 day per athlete and transition type:")
print(gaps_gt1_by_athlete_type.head(30))

# Optional pivot view: one row per athlete, one column per transition type
gaps_gt1_pivot = (
    gaps_gt1_by_athlete_type
    .pivot(index="Athlete ID", columns="transition", values="gaps_gt_1")
    .fillna(0)
    .astype(int)
)

print("\nPivot table (gaps > 1 day by transition type):")
print(gaps_gt1_pivot.head(10))

Gaps > 1 day per athlete and transition type:
    Athlete ID transition  gaps_gt_1
1            0       1->1          6
0            0       0->1          1
2            1       0->1          2
3            1       1->0          1
5            2       0->1          3
6            2       1->0          3
4            2       0->0          2
7            2       1->1          1
9            3       0->1          2
10           3       1->0          2
8            3       0->0          1
11           3       1->1          1
13           4       0->1          4
12           4       0->0          3
14           4       1->0          3
15           4       1->1          3
16           5       0->0          1
17           5       0->1          1
18           6       0->1          2
19           6       1->0          2
20           6       1->1          2
24           7       1->1          3
22           7       0->1          2
21           7       0->0          1
23           7       1->0          1
27           8       1->1          5
25           8       0->1          2
26           8       1->0          2
29           9       0->1         18
30           9       1->0         18

Pivot table (gaps > 1 day by transition type):
transition  0->0  0->1  1->0  1->1
Athlete ID
0              0     1     0     6
1              0     2     1     0
2              2     3     3     1
3              1     2     2     1
4              3     4     3     3
5              1     1     0     0
6              0     2     2     2
7              1     2     1     3
8              0     2     2     5
9              1    18    18     5

In [14]:
print("\nSanity checks:")
print("Negative gaps:", (processed_df["transition_period_days"] < 0).sum())
print("Missing transition values:", processed_df["transition"].isna().sum())
print("Missing transition_period_days:", processed_df["transition_period_days"].isna().sum())

Sanity checks:
Negative gaps: 0
Missing transition values: 0
Missing transition_period_days: 0

In [21]:
onset_df = processed_df.copy()
onset_df = onset_df.sort_values(["Athlete ID", "Date"]).reset_index(drop=True)

print("Rows kept for onset modeling:", len(onset_df))

Rows kept for onset modeling: 42766

In [51]:
onset_df = processed_df.copy()
onset_df = onset_df.sort_values(["Athlete ID", "Date"]).dropna(subset=["Date"]).reset_index(drop=True)

horizon_days = 40

In [60]:
def build_onset_label(group, horizon_days):
    # Already grouped by athlete, so only sort by Date
    group = group.sort_values("Date").copy()

    t = group["Date"].to_numpy()
    injuries = group["injury"].astype(int).to_numpy()
    labels = np.zeros(len(group), dtype=int)

    for i, current_t in enumerate(t):
        future_mask = (t > current_t) & (t <= current_t + horizon_days)
        labels[i] = int(injuries[future_mask].any())

    group["y_onset"] = labels
    return group

# Safety: recover Athlete ID if onset_df was overwritten without it
if "Athlete ID" not in onset_df.columns:
    onset_df["Athlete ID"] = processed_df["Athlete ID"]

onset_df = (
    onset_df
    .groupby("Athlete ID", group_keys=False)
    .apply(build_onset_label, horizon_days=horizon_days)
    .reset_index(drop=True)
)

# Keep alias expected by downstream cells
onset_df["y"] = onset_df["y_onset"]

print("Onset positives (y=1):", onset_df["y_onset"].sum())
print("Onset prevalence:", onset_df["y_onset"].mean())
print(onset_df["y_onset"].value_counts())

Onset positives (y=1): 5988
Onset prevalence: 0.14001777112659589
y_onset
0    36778
1     5988
Name: count, dtype: int64

In [ ]:
window_days = 20

# Features you want to use in the window
feature_cols = [
    col for col in processed_df.columns
    if col not in ["Date", "y", "transition"]
]

    
# Make sure these columns exist in onset_df
feature_cols = [col for col in feature_cols if col in onset_df.columns]

def build_windows(group, window_days=20):
    group = group.sort_values("Date").reset_index(drop=True)
    samples = []

    # Robust athlete id retrieval (works even if grouped key is in index)
    athlete_id = group["Athlete ID"].iloc[0] if "Athlete ID" in group.columns else group.name

    for i in range(len(group)):
        anchor_date = group.loc[i, "Date"]
        start_date = anchor_date - (window_days - 1)

        window = group[(group["Date"] >= start_date) & (group["Date"] <= anchor_date)].copy()

        if window.empty:
            continue

        # Keep the latest record for each date inside the window
        window = window.drop_duplicates(subset=["Date"], keep="last")

        sample = {
            "Athlete ID": athlete_id,
            "anchor_date": anchor_date,
            "y": group.loc[i, "y"],
            "n_obs_in_window": len(window),
            "window_start": window["Date"].min(),
            "window_end": window["Date"].max(),
        }

        # Store the raw window values as a list of rows
        sample["window_df"] = window[feature_cols].copy()

        samples.append(sample)

    return pd.DataFrame(samples)

# Ensure Athlete ID exists as a regular column before groupby
if "Athlete ID" not in onset_df.columns:
    if onset_df.index.name == "Athlete ID" or "Athlete ID" in (onset_df.index.names or []):
        onset_df = onset_df.reset_index()
    else:
        onset_df = onset_df.copy()
        onset_df["Athlete ID"] = processed_df["Athlete ID"].values

windowed_df = (
    onset_df
    .groupby("Athlete ID", group_keys=False)
    .apply(build_windows, window_days=window_days)
    .reset_index(drop=True)
)

print("Number of windowed samples:", len(windowed_df))
print(windowed_df[["Athlete ID", "anchor_date", "y", "n_obs_in_window"]].head())

KeyError: 'Athlete ID'

In [ ]:
max_window_len = 20

def pad_window(window_df, feature_cols, max_len=20):
    window_values = window_df[feature_cols].copy().to_numpy()

    if len(window_values) > max_len:
        window_values = window_values[-max_len:]

    pad_length = max_len - len(window_values)

    if pad_length > 0:
        pad_array = np.zeros((pad_length, len(feature_cols)))
        window_values = np.vstack([pad_array, window_values])

    return window_values

X = []
y = []

for _, row in windowed_df.iterrows():
    X.append(pad_window(row["window_df"], feature_cols, max_len=max_window_len))
    y.append(row["y"])

X = np.array(X)
y = np.array(y)

print("X shape:", X.shape)
print("y shape:", y.shape)

In [ ]:
print("Positive samples:", y.sum())
print("Negative samples:", len(y) - y.sum())
print("Positive rate:", y.mean())